---
name: CI
on: [push,pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '1.15.0'
    - run: go version
    - run: go mod download

    - name: golangci-lint
      run: |
        bash ci/install-golangci-lint.sh
        golangci-lint run
    - name: test
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      run: |
        bash ci/test.sh go-convmap
